services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ipms
      POSTGRES_USER: ipms
      POSTGRES_PASSWORD: ipms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
